//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jamuro.AdventureWorks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jamuro.AdventureWorks.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Includes.
        /// </summary>
        public static string AddIncludes {
            get {
                return ResourceManager.GetString("AddIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected by N+1 Problem.
        /// </summary>
        public static string AffectedByN1Problem {
            get {
                return ResourceManager.GetString("AffectedByN1Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Bikes.
        /// </summary>
        public static string AllBikes {
            get {
                return ResourceManager.GetString("AllBikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Bikes with check for existence by using Any() over all rows.
        /// </summary>
        public static string AllBikesWithCheckAllAnyTitle {
            get {
                return ResourceManager.GetString("AllBikesWithCheckAllAnyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Bikes with check for existence by using Count() over all rows.
        /// </summary>
        public static string AllBikesWithCheckAllCountTitle {
            get {
                return ResourceManager.GetString("AllBikesWithCheckAllCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Bikes with check for existence by using Any() with filter.
        /// </summary>
        public static string AllBikesWithCheckAnyTitle {
            get {
                return ResourceManager.GetString("AllBikesWithCheckAnyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All BIkes with check for existence by retrieving only one record.
        /// </summary>
        public static string AllBikesWithCheckOneTitle {
            get {
                return ResourceManager.GetString("AllBikesWithCheckOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Bikes with check for existence by using Exists().
        /// </summary>
        public static string AllBikesWithCheckWIthExistsTitle {
            get {
                return ResourceManager.GetString("AllBikesWithCheckWIthExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results from &quot;Add Includes + No Tracking + Only Required fields&quot; executed with &quot;SQL Query Stress&quot; tool over 100 iterations.
        /// </summary>
        public static string AllImprovForBestQueryStressComments {
            get {
                return ResourceManager.GetString("AllImprovForBestQueryStressComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results from &quot;Add Includes + No Tracking&quot; executed with &quot;SQL Query Stress&quot; tool over 100 iterations.
        /// </summary>
        public static string AllImprovForGoodQueryStressComments {
            get {
                return ResourceManager.GetString("AllImprovForGoodQueryStressComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORM Demo.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application demo by using SQL Server 2016 Adventure Works sample DB, MVC and EF..
        /// </summary>
        public static string ApplicationSubtitle {
            get {
                return ResourceManager.GetString("ApplicationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid N+1 Problem by using &quot;Includes&quot;.
        /// </summary>
        public static string AvoidN1ProblemWithIncludes {
            get {
                return ResourceManager.GetString("AvoidN1ProblemWithIncludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected by bad practice to check pre-existence of rows.
        /// </summary>
        public static string BadPractiseForCheckingExistence {
            get {
                return ResourceManager.GetString("BadPractiseForCheckingExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        public static string Best {
            get {
                return ResourceManager.GetString("Best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bikes.
        /// </summary>
        public static string Bikes {
            get {
                return ResourceManager.GetString("Bikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de Ejecucion.
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Tools.
        /// </summary>
        public static string ExternalTools {
            get {
                return ResourceManager.GetString("ExternalTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bien.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://jamuro-blog.azurewebsites.net.
        /// </summary>
        public static string JamuroBlog {
            get {
                return ResourceManager.GetString("JamuroBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to José A. Muro.
        /// </summary>
        public static string JamuroName {
            get {
                return ResourceManager.GetString("JamuroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can still improve performance by enhancing Repositories or LINQ queries in order to return only specific required fields.
        /// </summary>
        public static string LinqImprovedByReturningSpecificSQLFields {
            get {
                return ResourceManager.GetString("LinqImprovedByReturningSpecificSQLFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LINQ query executed in this view is good enough but yet it can be improved.
        /// </summary>
        public static string LinqOkButCanBeImproved {
            get {
                return ResourceManager.GetString("LinqOkButCanBeImproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying SQL is returning all the fields for each SQL table.
        /// </summary>
        public static string LinqReturningAllSqlFields {
            get {
                return ResourceManager.GetString("LinqReturningAllSqlFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Resources.
        /// </summary>
        public static string MoreResources {
            get {
                return ResourceManager.GetString("MoreResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Expensive Bikes.
        /// </summary>
        public static string MostExpensiveBikes {
            get {
                return ResourceManager.GetString("MostExpensiveBikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results from LINQ query executed with &quot;SQL Query Stress&quot; tool over 100 iterations (filter by 10 most expensive bikes is not performed inside database).
        /// </summary>
        public static string MostExpensiveBikesForBadQueryStressComments {
            get {
                return ResourceManager.GetString("MostExpensiveBikesForBadQueryStressComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results from LINQ query with &quot;Top 10 injected in SQL&quot; executed with &quot;SQL Query Stress&quot; tool over 100 iterations.
        /// </summary>
        public static string MostExpensiveBikesForGoodQueryStressComments {
            get {
                return ResourceManager.GetString("MostExpensiveBikesForGoodQueryStressComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N+1 Problem.
        /// </summary>
        public static string N1Problem {
            get {
                return ResourceManager.GetString("N1Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not affected when checking pre-existence of rows.
        /// </summary>
        public static string NotAffectedForCheckingExistence {
            get {
                return ResourceManager.GetString("NotAffectedForCheckingExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tracking.
        /// </summary>
        public static string NoTracking {
            get {
                return ResourceManager.GetString("NoTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Spanish Version.
        /// </summary>
        public static string OnlySpanishVersion {
            get {
                return ResourceManager.GetString("OnlySpanishVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrict SQL Fields.
        /// </summary>
        public static string RestrictSQLFields {
            get {
                return ResourceManager.GetString("RestrictSQLFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only SQL fields that are employed in business model.
        /// </summary>
        public static string SelectOnlySqlEmployedFields {
            get {
                return ResourceManager.GetString("SelectOnlySqlEmployedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Details.
        /// </summary>
        public static string ShowHideDetails {
            get {
                return ResourceManager.GetString("ShowHideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Tracking.
        /// </summary>
        public static string SkipTracking {
            get {
                return ResourceManager.GetString("SkipTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Indexes.
        /// </summary>
        public static string SQLIndexes {
            get {
                return ResourceManager.GetString("SQLIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Monitorization.
        /// </summary>
        public static string SQLMonitorization {
            get {
                return ResourceManager.GetString("SQLMonitorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Query Optimization.
        /// </summary>
        public static string SQLQueryOptimization {
            get {
                return ResourceManager.GetString("SQLQueryOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Resource Optimization.
        /// </summary>
        public static string SQLResourceOptimization {
            get {
                return ResourceManager.GetString("SQLResourceOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL returning only top {0} bikes.
        /// </summary>
        public static string SQLReturningOnlyTopBikes {
            get {
                return ResourceManager.GetString("SQLReturningOnlyTopBikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected by bad SQL returning all products and then, filtering by {0} most expensive.
        /// </summary>
        public static string SQLTopMostExpensiveBikesBadMsg {
            get {
                return ResourceManager.GetString("SQLTopMostExpensiveBikesBadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologies.
        /// </summary>
        public static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therefore.
        /// </summary>
        public static string Therefore {
            get {
                return ResourceManager.GetString("Therefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 Most Expensive Bikes.
        /// </summary>
        public static string Top10MostExpensiveBikes {
            get {
                return ResourceManager.GetString("Top10MostExpensiveBikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Includes.
        /// </summary>
        public static string WithIncludes {
            get {
                return ResourceManager.GetString("WithIncludes", resourceCulture);
            }
        }
    }
}
